### ISSUE TITLE
Предварительная оценка (по вопросам в тг - @rendizi) 

### ISSUE THREAD

**Issue by abglnv** [anaskozyr/distributed-calculator#2]
- Существует Readme документ, в котором описано, как запустить систему и как ей пользоваться. 10/10
- Программа запускается и все примеры с вычислением арифметических выражений корректно работают 10/10
- Программа запускается и выполняются произвольные примеры с вычислением арифметических выражений 10/10
- Можно перезапустить любой компонент системы и система корректно обработает перезапуск (результаты сохранены, система продолжает работать) 10/10
- Система предосталяет графический интерфейс для вычисления арифметических выражений 10/10
- Реализован мониторинг воркеров 0/20
- Реализован интерфейс для мориторинга воркеров 0/10
- Вам понятна кодовая база и структура проекта 10/10
- У системы есть документация со схемами, которая наглядно отвечает на вопрос: "Как это все работает 10/10
- Выражение должно иметь возможность выполняться разными агентами 10/10
<h1>Total: 80/110</h1>
Имеются траблы с делением на 0.

**Comment by anaskozyr** [comment]
Добрый день!

Огромное Вам спасибо за ваш feeback.

Я уже внесла изменения в код для  обработки  деления на 0.  


![изображение](https://github.com/anaskozyr/distributed-calculator/assets/159546830/4a0f1938-a299-474b-b160-5a417b9f1d92)

**Comment by rendizi** [comment]
День добрый, понял твой подход к обработке деления на ноль - возвращать inf (9223372036854775807). Я приму это, но, к слову, это не пределы, чтобы деление на ноль было бесконечностью, и я ожидал ошибки.

**Comment by abglnv** [comment]
День добрый, понял твой подход к обработке деления на ноль - возвращать inf (9223372036854775807). Я приму это, но, к слову, это не пределы, чтобы деление на ноль было бесконечностью, и я ожидал ошибки.
